# Extra autostart processes
# exec-once = uwsm-app -- my-service

# Korean input method
exec-once = fcitx5 -d --replace

# Load personal window rules after Omarchy defaults
source = ~/.config/hypr/windows.conf
