# Reference: https://github.com/i3/i3/blob/next/etc/config

# Start Aerospace at login
start-at-login = true

# i3 doesn't have "normalizations" feature that why we disable them here.
# But the feature is very helpful.
# Normalizations eliminate all sorts of weird tree configurations that don't make sense.
# Give normalizations a chance and enable them back.
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Possible values : tiles | accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

after-startup-command = [
    'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0 blacklist="iPhone Mirroring"'
]

[mode.main.binding]

    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'

    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    alt-f = 'fullscreen'

    alt-s = 'layout v_accordion' # 'layout stacking' in i3
    alt-w = 'layout h_accordion' # 'layout tabbed' in i3
    alt-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

    alt-shift-space = 'layout floating tiling' # 'floating toggle' in i3

    # See: https://nikitabobko.github.io/AeroSpace/commands#resize
    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'

    # Not supported, because this command is redundant in AeroSpace mental model.
    # See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
    #alt-space = 'focus toggle_tiling_floating'

    # `focus parent`/`focus child` are not yet supported, and it's not clear whether they
    # should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
    # alt-a = 'focus parent'

    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'
    alt-7 = 'workspace 7'
    alt-8 = 'workspace 8'
    alt-9 = 'workspace 9'
    alt-0 = 'workspace 10'

    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    alt-shift-6 = 'move-node-to-workspace 6'
    alt-shift-7 = 'move-node-to-workspace 7'
    alt-shift-8 = 'move-node-to-workspace 8'
    alt-shift-9 = 'move-node-to-workspace 9'
    alt-shift-0 = 'move-node-to-workspace 10'

    alt-shift-s = 'mode settings'
    alt-shift-o = 'mode open'

[workspace-to-monitor-force-assignment]
    6 = ['secondary', 'main']

[mode.open.binding]
    i = ['exec-and-forget open -a "IntelliJ IDEA"', 'mode main']
    c = ['exec-and-forget open -a "Cursor.app"', 'mode main']
    p = ['exec-and-forget open -a "PyCharm.app"', 'mode main']
    v = ['exec-and-forget open -a "Visual Studio Code.app"', 'mode main']
    f = ['exec-and-forget open -a "Finder"', 'mode main']
    b = ['exec-and-forget open "https://www.google.com"', 'mode main']

    esc = 'mode main'

[mode.settings.binding]
    h = 'resize width +50'
    j = 'resize height +50'
    k = 'resize height -50'
    l = 'resize width -50'

    r = ['flatten-workspace-tree', 'mode main'] # reset layout
    backspace = ['close-all-windows-but-current', 'mode main']
    enter = ['reload-config', 'mode main']

    alt-shift-h = ['join-with left', 'mode main']
    alt-shift-j = ['join-with down', 'mode main']
    alt-shift-k = ['join-with up', 'mode main']
    alt-shift-l = ['join-with right', 'mode main']

    esc = 'mode main'



# Chrome, Notion, ChatGPT to workspace 1
[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-id = 'notion.id'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-id = 'com.openai.chat'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-id = 'company.thebrowser.Browser'
run = 'move-node-to-workspace 1'

# Dev : IDE's to workspace 2
[[on-window-detected]]
if.app-id = 'com.jetbrains.pycharm'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'com.jetbrains.intellij'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'com.todesktop.230313mzl4w4u92'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = 'move-node-to-workspace 2'

# Goodnotes to workspace 3
[[on-window-detected]]
if.app-id = 'com.goodnotesapp.x'
run = 'move-node-to-workspace 3'

# Messangers to workspace 5
[[on-window-detected]]
if.app-id = 'com.kakao.KakaoTalkMac'
run = ['layout floating', 'move-node-to-workspace 5']

[[on-window-detected]]
if.app-id = 'com.hnc.Discord'
run = ['layout floating', 'move-node-to-workspace 5']

[[on-window-detected]]
if.app-id = 'com.apple.ScreenContinuity'
run = ['layout floating', 'move-node-to-workspace 5']

# Finder to workspace 9
[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = 'move-node-to-workspace 9'

# Terminal to workspace 10
[[on-window-detected]]
if.app-id = 'com.googlecode.iterm2'
run = 'move-node-to-workspace 10'
